/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class uk_me_rochester_Aurora */

#ifndef _Included_uk_me_rochester_Aurora
#define _Included_uk_me_rochester_Aurora
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     uk_me_rochester_Aurora
 * Method:    runService
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_uk_me_rochester_Aurora_runService
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
